<?php



/**
 * @file
 * Main module file for islandora iiif manifests.
 */

define('ISLANDORA_IIIF_MANIFEST_HOOK', 'islandora_get_iiif_manifest');

/**
 * Implements hook_init().
 */
function islandora_iiif_init() {
  require_once __DIR__ . "/vendor/autoload.php";
}

/**
 * Implements hook_menu().
 */
function islandora_iiif_menu() {
  return array(
    'islandora_iiif/%islandora_object/%/%/%/%' => array(
      'page callback' => 'islandora_iiif_proxied_image_response',
      'page arguments' => array(1, 2, 3, 4, 5),
      'type' => MENU_CALLBACK,
      'access callback' => 'islandora_object_access',
      'access arguments' => array(ISLANDORA_VIEW_OBJECTS, 1),
      'load arguments' => array(1),
    ),
    'islandora_iiif/%islandora_object/manifest' => array(
      'page callback' => 'islandora_iiif_manifest_callback',
      'page arguments' => array(1),
      'file' => 'includes/manifest.inc',
      'type' => MENU_CALLBACK,
      'access callback' => 'islandora_object_access',
      'access arguments' => array(ISLANDORA_VIEW_OBJECTS, 1),
      'load arguments' => array(1),
    ),
    'islandora_iiif/%islandora_object/sequence/%' => array(
      'page callback' => 'islandora_iiif_sequence_callback',
      'page arguments' => array(1),
      'file' => 'includes/sequence.inc',
      'type' => MENU_CALLBACK,
      'access callback' => 'islandora_object_access',
      'access arguments' => array(ISLANDORA_VIEW_OBJECTS, 1),
      'load arguments' => array(1),
    ),
    'islandora_iiif/%islandora_object/canvas/%' => array(
      'page callback' => 'islandora_iiif_canvas_callback',
      'page arguments' => array(1),
      'file' => 'includes/canvas.inc',
      'type' => MENU_CALLBACK,
      'access callback' => 'islandora_object_access',
      'access arguments' => array(ISLANDORA_VIEW_OBJECTS, 1),
      'load arguments' => array(1),
    ),
    'islandora_iiif/collection/%islandora_object' => array(
      'page callback' => 'islandora_iiif_collection_callback',
      'file' => 'includes/collection.inc',
      'page arguments' => array(2),
      'type' => MENU_CALLBACK,
      'access callback' => 'islandora_object_access',
      'access arguments' => array(ISLANDORA_VIEW_OBJECTS, 2),
      'load arguments' => array(2),
    ),
    'islandora_iiif/collection/%islandora_object/%' => array(
      'page callback' => 'islandora_iiif_collection_callback',
      'file' => 'includes/collection.inc',
      'page arguments' => array(2, 3),
      'type' => MENU_CALLBACK,
      'access callback' => 'islandora_object_access',
      'access arguments' => array(ISLANDORA_VIEW_OBJECTS, 2),
      'load arguments' => array(2),
    ),
    'admin/islandora/tools/internet_iiif_admin' => array(
      'title' => 'IIIF Module configuration',
      'description' => 'Configure the IIIF Module.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_iiif_admin_settings_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    )
  );
}

/**
 *
 */
function islandora_iiif_rootcollection_access($op, $object, $user = NULL) {
  // Get root as we have it configured globally. We can always get
  // islandora:root directly via the PID specific collection manifest.
  $root_pid = variable_get('islandora_repository_pid', 'islandora:root');
  if ($object = islandora_object_load($root_pid)) {
    return islandora_object_access($op, $object, $user);
  }
  return FALSE;
}


/**
 * Implements hook_islandora_derivative().
 */
function islandora_iiif_islandora_derivative() {

    return array(
        array(
            'source_dsid' => 'MODS',
            'destination_dsid' => 'MANIFEST',
            'weight' => 0,
            'function' => array(
                'islandora_iiif_create_manifest',
            ),
            'file' => "includes/derivatives.inc",
        )
    );
}
