<?php

/**
 * @file
 * Install for the islandora_iiif_manifests module.
 */


function islandora_iiif_manifests_uninstall() {

  $variables = array(
    'islandora_handle_debug_mode',
    'islandora_handle_server_admin_password',
    'islandora_handle_server_admin_username',
    'islandora_handle_server_prefix',
    'islandora_handle_server_url',
    'islandora_handle_handler',
    'islandora_handle_use_alias',
  );
  array_walk($variables, 'variable_del');

}