<?php



/**
 * @file
 * Main module file for islandora iiif manifests.
 */

define('ISLANDORA_IIIF_MANIFEST_HOOK', 'islandora_get_iiif_manifest');

/**
 * Implements hook_menu().
 */
function islandora_iiif_manifests_menu() {
  return array(
      'islandora_iiif_manifests/%islandora_object/manifest' => array(
      'page callback' => 'islandora_iiif_manifests_create_manifest_json',
      'page arguments' => array(1),
      'file' => 'includes/manifest.inc',
      'type' => MENU_CALLBACK,
      'access callback' => TRUE
      ),
      'islandora_iiif_manifests/%islandora_object/canvas' => array(
          'page callback' => 'islandora_iiif__manifests_create_canvas_json',
          'page arguments' => array(1),
          'file' => 'includes/manifest.inc',
          'type' => MENU_CALLBACK,
          'access callback' => TRUE
      ),
      'admin/islandora/tools/islandora_iiif_manifests_admin' => array(
          'title' => 'IIIF manifest module configuration',
          'description' => 'Configure the IIIF Module.',
          'page callback' => 'drupal_get_form',
          'page arguments' => array('islandora_iiif_manifests_admin_settings_form'),
          'access arguments' => array('administer site configuration'),
          'file' => 'includes/admin.form.inc',
          'type' => MENU_NORMAL_ITEM,
      )
  );
}


/**
 * Implements hook_CMODEL_PID_islandora_get_iiif_manifest().
 */
function islandora_iiif_manifests_islandora_sp_basic_image_islandora_get_iiif_manifest($object) {

    module_load_include('inc', 'islandora_iiif_manifests', 'includes/models/basic_image');
    $array = islandora_iiif_manifest_create_basic_image_canvas($object);

    return $array;
}


/**
 * Implements hook_CMODEL_PID_islandora_get_iiif_manifest().
 */
function islandora_iiif_manifests_islandora_sp_large_image_cmodel_islandora_get_iiif_manifest($object) {

    module_load_include('inc', 'islandora_iiif_manifests', 'includes/models/large_image');
    $array = islandora_iiif_manifest_create_large_image_canvas($object);

    return $array;
}

/**
 * Implements hook_CMODEL_PID_islandora_get_iiif_manifest().
 */
function islandora_iiif_manifests_islandora_compoundCModel_islandora_get_iiif_manifest($object) {

    module_load_include('inc', 'islandora_iiif_manifests', 'includes/models/compound');
    $array = islandora_iiif_manifest_create_compound_manifest($object);


    return $array;
}

/**
 * Implements hook_CMODEL_PID_islandora_get_iiif_manifest().
 */
function islandora_iiif_manifests_islandora_collectionCModel_islandora_get_iiif_manifest($object) {

    module_load_include('inc', 'islandora_iiif_manifests', 'includes/models/collection');
    $array = islandora_iiif_manifest_create_collection_manifest($object);

    //dpm( $object,"collection");

    return $array;
}


/**
 * Implements hook_CMODEL_PID_islandora_get_iiif_manifest().
 */
function islandora_iiif_manifests_islandora_bookCModel_islandora_get_iiif_manifest($object) {

    module_load_include('inc', 'islandora_iiif_manifests', 'includes/models/book');
    $array = islandora_iiif_manifest_create_book_manifest($object);

    return $array;
}

/**
 * Implements hook_CMODEL_PID_islandora_get_iiif_manifest().
 */
function islandora_iiif_manifests_islandora_pageCModel_islandora_get_iiif_manifest($object) {

    module_load_include('inc', 'islandora_iiif_manifests', 'includes/models/page');
    $array = islandora_iiif_manifest_create_page_canvas($object);

    return $array;
}


/**
 * Implements hook_CMODEL_PID_islandora_get_iiif_manifest().
 */
function islandora_iiif_manifests_islandora_newspaperCModel_islandora_get_iiif_manifest($object) {

    // Display Newspaper as a colleciton. Each issue is a manifest with its pages
    module_load_include('inc', 'islandora_iiif_manifests', 'includes/models/newspaper');

    $array = islandora_iiif_manifest_create_newspaper_manifest($object);

    return $array;
}

/**
 * Implements hook_CMODEL_PID_islandora_get_iiif_manifest().
 */
function islandora_iiif_manifests_islandora_newspaperIssueCModel_islandora_get_iiif_manifest($object) {

    module_load_include('inc', 'islandora_iiif_manifests', 'includes/models/issue');
    $array = islandora_iiif_manifest_create_issue_manifest($object);

    return $array;
}


/**
 * Implements hook_CMODEL_PID_islandora_get_iiif_manifest().
 */
function islandora_iiif_manifests_islandora_newspaperPageCModel_islandora_get_iiif_manifest($object) {

    module_load_include('inc', 'islandora_iiif_manifests', 'includes/models/page');
    $array = islandora_iiif_manifest_create_page_canvas($object);

    return $array;
}


function islandora_iiif_manifests_islandora_get_iiif_manifest($object) {
    module_load_include('inc', 'islandora_iiif_manifests', 'includes/manifest');

    $manifest_container = islandora_iiif_manifest_create_container_manifest($object);

    return $manifest_container;
}


/**
 * Implements hook_detail_tools_block_view().
 */
function islandora_iiif_manifests_detail_tools_block_view() {
  $block = array();

  if (arg(1) == 'object' && islandora_is_valid_pid(arg(2))) {
    $obj = islandora_object_load(arg(2));
    
    $show_menu = FALSE;
    if (allowedCModel($obj)) {
      if (islandora_object_access(ISLANDORA_VIEW_OBJECTS, $obj)) {
        $show_menu = TRUE;
      }
    }

    if ($show_menu) {
      $modpath = drupal_get_path('module', 'islandora_iiif_manifests');
      drupal_add_css($modpath . '/css/iiif_menu.css');
      drupal_add_js($modpath . '/js/iiif_menu.js');

      $manifestkey = (count(array_intersect($obj->models, array('islandora:newspaperCModel', 'islandora:collectionCModel'))) > 0) ? "collection" : "manifest";
      $manifest_url = url('/islandora_iiif_manifests/' . $obj->id . '/manifest', array('absolute' => TRUE));
      $mirador_url = url('https://webpresentations-a.universiteitleiden.nl/mirador/', array('external' => TRUE, 'query' => array($manifestkey => $manifest_url)));
      $additional = '<DIV class="iiif-additional">';
      $additional .= '<DIV class="menu">';
      $additional .= '<H3>IIIF</H3>';
      $additional .= '<DIV class="explain">';
      $additional .= t('View and use this object outside of this site using:');
      $additional .= '</DIV>';
      $additional .= '<A class="iiifmanifest" href="' . $manifest_url . '" target="_blank">';
      $additional .= '<IMG src="/' . $modpath . '/images/manifest3.png"/></A>';
      $additional .= '&nbsp;';
      $additional .= '<A href="' . $mirador_url . '" target="_blank"><IMG src="/' . $modpath . '/images/mirador.png"/></A>';
      $additional .= '</DIV>';
      $additional .= '</DIV>';

      // Put this in a item list.
      $block['list'] = array(
        '#type' => 'ul',
        '#attributes' => array('class' => array('dc-detail-tools', 'ubl-detail-tools')),
        '#items' => array(
          array(
            'data' => l(
              '<span>link</span><i class="fa fa-eye" aria-hidden="true"></i>',
              $url,
              array('attributes' => array('title' => 'IIIF'),'html' => TRUE)
            ),
            'weight' => 999,
          ),
        ),
        '#theme' => 'item_list',
      );
      $block['iiifadditional'] = array(
        '#type' => 'markup',
        '#markup' => $additional,
      );
    }
  }
  return $block;
}

