<?php
/**
 * @file
 * Defines functions used when constructing derivatives.
 */

/**
 * Decides which derivative function to call and runs it.
 *
 * @param AbstractObject $object
 *   The object to run the derivative function for.
 * @param string $dsid
 *   The DSID to run the derivative function for.
 */
function islandora_iiif_create_manifest(AbstractObject $object, $dsid) {
    echo "Going to create manifest!";
}